services:

  tests:
    profiles:
      - tests
    container_name: wallet_tests
    build:
      context: .
      dockerfile: Dockerfile.tests
    image: wallet_tests
    env_file:
      - ./dev.env
    environment:
      TESTING: "TRUE"
      BACKEND_PVT_K: "mock"
      BACKEND_PUB_K: "mock"
    volumes:
      - ./wallet:/app/wallet
      - ./tests:/app/tests
    tty: true
    networks:
      - pg-ext-net

  wallet_api:
    profiles:
      - dev
    container_name: wallet_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./dev.env
    volumes:
      - ./wallet:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    tty: true
    networks:
      - pg-ext-net

  rsa_api:
    profiles:
      - dev
    container_name: rsa_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./dev.env
    volumes:
      - ./wallet:/app
    ports:
      - "9001:9001"
    depends_on:
      - mongo
    tty: true
    networks:
      - pg-ext-net
      
  mongo:
    profiles:
      - dev
    image: mongo@sha256:4e6a14311567d04fab842b9df6d2b88b8425362632f262da208c97af167df93c
    ports:
      - 27017:27017
    networks:
      - pg-ext-net

  mongo-express:
    profiles:
      - dev
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH=false
    networks:
      - pg-ext-net

networks:
  pg-ext-net:
    external:
      name: crypto-backend_pg-net