name: Deploy Wallet API

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install make

      - name: Get Coverage
        run: make coverage

      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      - name: Upload coverage to SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        run: make sonar

  deploy:
    runs-on: ubuntu-22.04
    needs: tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install make

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Setup Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8' 

      - name: Build project for production
        run: make prod-build-deps

      - name: Zip project for lambda
        run: make zip

      - name: Deploy
        env:
            TF_VAR_MONGO_URI: ${{ secrets.MONGO_URI }}
            TF_VAR_environment: prod
            TF_VAR_PG_HOST: ${{ secrets.PG_HOST }}
            TF_VAR_PG_USER: ${{ secrets.PG_USER }}
            TF_VAR_PG_PASS: ${{ secrets.PG_PASS }}
            TF_VAR_PG_DB: ${{ secrets.PG_DB }}
            TF_VAR_PG_SSL: True
        run: |
          make tf-init
          make tf-apply
